/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  AddressLike,
  BaseContract,
  BigNumberish,
  BytesLike,
  ContractMethod,
  ContractRunner,
  EventFragment,
  FunctionFragment,
  Interface,
  Listener,
  Result,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedContractMethod,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedLogDescription,
} from './common';

export interface _KamiMarketRegistrySystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'cancelOwnershipHandover'
      | 'completeOwnershipHandover'
      | 'deprecate'
      | 'execute'
      | 'owner'
      | 'ownershipHandoverExpiresAt'
      | 'renounceOwnership'
      | 'requestOwnershipHandover'
      | 'setEnabled'
      | 'setFeeRate'
      | 'setFeeRecipient'
      | 'setMaxOrders'
      | 'setPurchaseCooldown'
      | 'setVault'
      | 'transferOwnership'
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'OwnershipHandoverCanceled'
      | 'OwnershipHandoverRequested'
      | 'OwnershipTransferred'
      | 'SystemDeprecated'
  ): EventFragment;

  encodeFunctionData(functionFragment: 'cancelOwnershipHandover', values?: undefined): string;
  encodeFunctionData(functionFragment: 'completeOwnershipHandover', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'deprecate', values?: undefined): string;
  encodeFunctionData(functionFragment: 'execute', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'ownershipHandoverExpiresAt', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(functionFragment: 'requestOwnershipHandover', values?: undefined): string;
  encodeFunctionData(functionFragment: 'setEnabled', values: [boolean]): string;
  encodeFunctionData(functionFragment: 'setFeeRate', values: [BigNumberish[]]): string;
  encodeFunctionData(functionFragment: 'setFeeRecipient', values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: 'setMaxOrders',
    functionFragment: 'setPurchaseCooldown',
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: 'setVault', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: 'cancelOwnershipHandover', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'completeOwnershipHandover', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'deprecate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'ownershipHandoverExpiresAt', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'requestOwnershipHandover', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setEnabled', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setFeeRate', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setFeeRecipient', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setPurchaseCooldown', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setVault', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
}

export namespace OwnershipHandoverCanceledEvent {
  export type InputTuple = [pendingOwner: AddressLike];
  export type OutputTuple = [pendingOwner: string];
  export interface OutputObject {
    pendingOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipHandoverRequestedEvent {
  export type InputTuple = [pendingOwner: AddressLike];
  export type OutputTuple = [pendingOwner: string];
  export interface OutputObject {
    pendingOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SystemDeprecatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface _KamiMarketRegistrySystem extends BaseContract {
  connect(runner?: ContractRunner | null): _KamiMarketRegistrySystem;
  waitForDeployment(): Promise<this>;

  interface: _KamiMarketRegistrySystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  cancelOwnershipHandover: TypedContractMethod<[], [void], 'payable'>;

  completeOwnershipHandover: TypedContractMethod<[pendingOwner: AddressLike], [void], 'payable'>;

  deprecate: TypedContractMethod<[], [void], 'nonpayable'>;

  execute: TypedContractMethod<[arg0: BytesLike], [string], 'nonpayable'>;

  owner: TypedContractMethod<[], [string], 'view'>;

  ownershipHandoverExpiresAt: TypedContractMethod<[pendingOwner: AddressLike], [bigint], 'view'>;

  renounceOwnership: TypedContractMethod<[], [void], 'payable'>;

  requestOwnershipHandover: TypedContractMethod<[], [void], 'payable'>;

  setEnabled: TypedContractMethod<[enabled: boolean], [void], 'nonpayable'>;

  setFeeRate: TypedContractMethod<[rate: BigNumberish[]], [void], 'nonpayable'>;

  setFeeRecipient: TypedContractMethod<[recipient: AddressLike], [void], 'nonpayable'>;

  setPurchaseCooldown: TypedContractMethod<[cooldown: BigNumberish], [void], 'nonpayable'>;

  setVault: TypedContractMethod<[vault: AddressLike], [void], 'nonpayable'>;

  transferOwnership: TypedContractMethod<[newOwner: AddressLike], [void], 'payable'>;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: 'cancelOwnershipHandover'
  ): TypedContractMethod<[], [void], 'payable'>;
  getFunction(
    nameOrSignature: 'completeOwnershipHandover'
  ): TypedContractMethod<[pendingOwner: AddressLike], [void], 'payable'>;
  getFunction(nameOrSignature: 'deprecate'): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'execute'
  ): TypedContractMethod<[arg0: BytesLike], [string], 'nonpayable'>;
  getFunction(nameOrSignature: 'owner'): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'ownershipHandoverExpiresAt'
  ): TypedContractMethod<[pendingOwner: AddressLike], [bigint], 'view'>;
  getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<[], [void], 'payable'>;
  getFunction(
    nameOrSignature: 'requestOwnershipHandover'
  ): TypedContractMethod<[], [void], 'payable'>;
  getFunction(
    nameOrSignature: 'setEnabled'
  ): TypedContractMethod<[enabled: boolean], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setFeeRate'
  ): TypedContractMethod<[rate: BigNumberish[]], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setFeeRecipient'
  ): TypedContractMethod<[recipient: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setPurchaseCooldown'
  ): TypedContractMethod<[cooldown: BigNumberish], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setVault'
  ): TypedContractMethod<[vault: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'transferOwnership'
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'payable'>;

  getEvent(
    key: 'OwnershipHandoverCanceled'
  ): TypedContractEvent<
    OwnershipHandoverCanceledEvent.InputTuple,
    OwnershipHandoverCanceledEvent.OutputTuple,
    OwnershipHandoverCanceledEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipHandoverRequested'
  ): TypedContractEvent<
    OwnershipHandoverRequestedEvent.InputTuple,
    OwnershipHandoverRequestedEvent.OutputTuple,
    OwnershipHandoverRequestedEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferred'
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: 'SystemDeprecated'
  ): TypedContractEvent<
    SystemDeprecatedEvent.InputTuple,
    SystemDeprecatedEvent.OutputTuple,
    SystemDeprecatedEvent.OutputObject
  >;

  filters: {
    'OwnershipHandoverCanceled(address)': TypedContractEvent<
      OwnershipHandoverCanceledEvent.InputTuple,
      OwnershipHandoverCanceledEvent.OutputTuple,
      OwnershipHandoverCanceledEvent.OutputObject
    >;
    OwnershipHandoverCanceled: TypedContractEvent<
      OwnershipHandoverCanceledEvent.InputTuple,
      OwnershipHandoverCanceledEvent.OutputTuple,
      OwnershipHandoverCanceledEvent.OutputObject
    >;

    'OwnershipHandoverRequested(address)': TypedContractEvent<
      OwnershipHandoverRequestedEvent.InputTuple,
      OwnershipHandoverRequestedEvent.OutputTuple,
      OwnershipHandoverRequestedEvent.OutputObject
    >;
    OwnershipHandoverRequested: TypedContractEvent<
      OwnershipHandoverRequestedEvent.InputTuple,
      OwnershipHandoverRequestedEvent.OutputTuple,
      OwnershipHandoverRequestedEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    'SystemDeprecated()': TypedContractEvent<
      SystemDeprecatedEvent.InputTuple,
      SystemDeprecatedEvent.OutputTuple,
      SystemDeprecatedEvent.OutputObject
    >;
    SystemDeprecated: TypedContractEvent<
      SystemDeprecatedEvent.InputTuple,
      SystemDeprecatedEvent.OutputTuple,
      SystemDeprecatedEvent.OutputObject
    >;
  };
}
