// Autogenerated using mud component-types
import { World } from '@mud-classic/recs';
import { createClientComponents, createContractComponents } from './registers';

export type Components = ReturnType<typeof createComponents>;

// define functions for registration
export function createComponents(world: World) {
  return {
    ...createClientComponents(world),
    ...createContractComponents(world),
  };
}
