export const TermsAndConditions = [
  `
                     Kamigotchi`,

  `        Terms and Conditions of Use`,
  ``,

  `Kamigotchi is a distributed fully onchain idle-MMORPG pet game comprising a gaming application built on a set of specially-developed smart contracts (each, a "Smart Contract") deployed on the Initia Interwoven Stack or such other supported blockchain network or Layer 2 scaling solution (each, the "relevant Blockchain Network"), where players breed, train, evolve and personalise digital companions known as “Kamis”, and compete/interact with other players. Kamigotchi records and executes all player actions on chain, which provides transparency, verifiable scarcity of in-game assets, and enhanced composability. Kamigotchi does not utilise off-chain data storage, allowing for a decentralised gaming experience, allowing players to be in full custody and control of their digital assets. The game operates on a dynamic on-chain economy and marketplace for digital resources, where users are able to earn rewards for their efforts. The game also allows players to own their own “Kamis” in the form of unique non-fungible collectible tokens based on the ERC-721 standard or other similar “non-fungible” token standard, tradeable in a peer-to-peer manner, with each non-fungible token irrevocably associated with a unique Uniform Resource Identifier JSON file containing metadata such as the name, description or image file stored on Arweave/IPFS or such other storage network and/or usage terms of the underlying intellectual property ("NFT"). The Kamigotchi distributed gaming application is operated by Asphodel LLC (the "Company", "we", or "us"). The Kamigotchi distributed gaming application will be visualised on the https://kamigotchi.io/ website that the user can interact with (the "Site"). The Kamigotchi gaming application, including the Smart Contracts and the Site, are collectively referred to in these Terms as (the "App"). Using the App, users can play the game, view their NFT, interact with the underlying Smart Contracts, and interact with other users in the Kamigotchi game ecosystem.
The Company is making the App, the Smart Contracts and the Site available to you. Before you use the App, the Smart Contracts, or the Site, however, you will need to agree to these Terms of Use and any terms and conditions incorporated herein by reference (collectively, these "Terms"). PLEASE READ THESE TERMS CAREFULLY BEFORE USING THE APP, THE SMART CONTRACTS, OR THE SITE. THESE TERMS GOVERN YOUR USE OF THE APP, THE SMART CONTRACTS, AND THE SITE, UNLESS WE HAVE EXECUTED A SEPARATE WRITTEN AGREEMENT WITH YOU FOR THAT PURPOSE. WE ARE ONLY WILLING TO MAKE THE APP, THE SMART CONTRACTS, AND THE SITE AVAILABLE TO YOU IF YOU ACCEPT ALL OF THESE TERMS. BY USING THE APP, THE SMART CONTRACTS, THE SITE, OR ANY PART OF THEM, OR BY CLICKING "I ACCEPT" IN AN ADJOINING BOX OR OTHERWISE INDICATING YOUR ACCEPTANCE TO THESE TERMS, YOU ARE CONFIRMING THAT YOU UNDERSTAND AND AGREE TO BE BOUND BY ALL OF THESE TERMS. IF YOU ARE ACCEPTING THESE TERMS ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, YOU REPRESENT THAT YOU HAVE THE LEGAL AUTHORITY TO ACCEPT THESE TERMS ON THAT ENTITY’S BEHALF, IN WHICH CASE "YOU" WILL MEAN THAT ENTITY. IF YOU DO NOT HAVE SUCH AUTHORITY, OR IF YOU DO NOT ACCEPT ALL OF THESE TERMS, THEN WE ARE UNWILLING TO MAKE THE APP, THE SMART CONTRACTS, OR THE SITE AVAILABLE TO YOU. IF YOU DO NOT AGREE TO THESE TERMS, YOU MAY NOT ACCESS OR USE THE APP, THE SMART CONTRACTS, OR THE SITE.
Supplemental terms and conditions or documents that may be posted on the Site or the App from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes to the Terms from time to time. We will alert you of any changes by updating the “Last Updated" date of these Terms, and you waive any right to receive specific notice of each such change. It is your responsibility to periodically review these Terms to stay informed of updates. You will be subject to and will be deemed to have been made aware of and to have accepted, the changes in any revised Terms by your continued use of the Site, the App, and the Smart Contracts after the date such revised Terms are posted.

    1. THE APP
        A. To most easily use the App, you may first install a web browser (such as the Google Chrome web browser) and an EVM wallet compatible with the ERC-20 and ERC-721 standards (or similar standards) on the relevant Blockchain Network, such as the MetaMask, Rabby or other similar electronic wallets. These electronic wallets allow you to purchase, store, and engage in transactions using cryptocurrency. You will not be able to engage in any transactions on the App other than through your selected electronic wallet, or other browser compatible with the relevant Blockchain Network.
        B. Transactions that take place via Smart Contracts are managed and confirmed via the relevant Blockchain Network. You understand that your public address on the relevant Blockchain Network will be made publicly visible whenever you engage in an interaction with Smart Contracts or otherwise interact with the App. For the avoidance of doubt and notwithstanding any of the provisions herein, we NEVER ask for or control any private key or passwords relating to your digital assets and/or selected electronic wallets.
        C. We neither own nor control any browser, electronic wallet, the relevant Blockchain Network, or any other third party site, product, or service that you might access, visit, or use for the purpose of enabling you to use the various features of the App. We will not be liable for the acts or omissions of any such third parties, nor will we be liable for any damage that you may suffer as a result of your transactions or any other interaction with any such third parties.
        D. You will be able to create an account (digital profile, address and history that allows you to control your assets and transactions) by launching the App. We reserve the right to remove, reclaim or change a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable. You are fully responsible for the security of your account and your selected electronic wallet (and other wallets and accounts on the relevant Blockchain Network).

    2. KAMIGOTCHI, KAMIS AND NFTS
        A. The Kamigotchi ecosystem encompasses a variety of gameplay environments which players can interact with in order to earn/receive resources for their engagement.
        B. The digital resources as well as NFTs received are freely tradeable on various virtual currency exchanges, and may be exchanged and accessed in a peer-to-peer manner by users. The digital resources and NFTs would have no useability outside of the Kamigotchi gaming ecosystem. The digital resources and NFTs do not have any tangible or physical manifestation.
        C. Over time, the Company intends to incrementally introduce additional competitions, contests, games or modules within the Kamigotchi ecosystem, and your interaction with any of the foregoing shall be in accordance with these Terms, including without limitation full compliance with Section 9.A hereof.

    3. SUPPORT, UPDATES, ALTERATIONS, DISCONTINUANCE
        A. The Company may, but has no obligation to, offer and subsequently amend, alter suspend or discontinue support services with regard to the App, the Smart Contracts, Site, any element of the Kamigotchi gaming ecosystem, in-game digital resources, NFTs, or UGC (as defined herein) on such terms as the Company may determine within its sole discretion. At all times, the Company retains the right to use and/or dispose of the App, the Smart Contracts, Site, any element of the Kamigotchi gaming ecosystem, in-game digital resources, NFTs, or UGC, at the Company's sole discretion, as the Company deems appropriate, including without limitation the right, without notice, to alter, modify, redesign, suspend or discontinue, at any time, any aspect or feature of the App, the Smart Contracts, Site, any element of the Kamigotchi gaming ecosystem, in-game digital resources, NFTs, or UGC.
        B. In particular, without limitation, the Company has the right, but no obligation, to maintain, modify and/or update the App, the Smart Contracts, Site, any element of the Kamigotchi gaming ecosystem, in-game digital resources, NFTs, or UGC at its sole discretion. The Company may, but has no obligation to, provide technical support in respect of the App, the Smart Contracts, Site, any element of the Kamigotchi gaming ecosystem, in-game digital resources, NFTs, or UGC. You acknowledge and agree that such maintenance, updates, alterations, modifications, redesigns, suspensions or discontinuations may affect (also including by limiting or terminating) the functionality of the App, the Smart Contracts, Site, any element of the Kamigotchi gaming ecosystem, in-game digital resources, NFTs, or UGC.
        C. The Company does not undertake to keep any the Site or any related domains and/or website updated. To the greatest extent permitted by law the Company does not accept liability for any loss or damage which may result either directly or indirectly from reliance by you upon the accuracy or currency of information contained in any of the Site or any related domains and/or website or in relation to any post, information, summaries of document, including without limitation where such loss or damage is a result of or contributed to by the negligence of the Company.

    4. BETA SOFTWARE AND SERVICES
        A. From time to time, the Company may offer certain new services or version(s) of the App, including without limitation preview services, new features to existing services, additional services, or pre-release version(s) of the App or service (collectively "Beta Services").
        B. If you elect to use any Beta Services, then your use of the Beta Services is subject to the following terms and conditions: (a) you acknowledge and agree that the Beta Services are pre-release version(s) and may not work properly; (b) you acknowledge and agree that your use of the Beta Services may expose you to unusual risks of operational failures or loss of assets, digital assets or information; (c) the Beta Services are provided "as is", "as available", and "with all faults", so we strongly suggest not to utilise these in mission critical environments; (d) the Company reserves the right to modify, change, or discontinue any aspect of the Beta Services at any time; (e) the final release versions of the Beta Services may change substantially, and programs that use or run with the Beta Services may not work with the final release versions or subsequent releases; (f) the Company may limit availability of customer service support time dedicated to support of the Beta Services; (g) you acknowledge and agree to provide prompt feedback regarding your experience with the Beta Services in a form reasonably requested by us, including information necessary to enable us to duplicate errors or problems you experience; and (h) you acknowledge and agree that the Company may track your interactions with the App, browsing behaviour, links clicked, items or services purchased, your device type, and to collect various data, including analytics, about how you use and interact with our Beta Services.

    5. GAMES OF SKILL
        A. By utilising the App (including participating in any competitions, contests and games thereon), Smart Contracts and the Site, each user acknowledges and agrees that he/she is participating in a game of skill. Games of skill are legal, as they are generally excluded from the ambit of gambling legislations around the world. The App, Smart Contracts and the Site may not be used for any form of illicit gambling, betting, or wagering (howsoever named).
        B. All competitions, contests and games offered on the App, Smart Contracts and the Site are games of skill. Winners and/or ranked players on the leader-board are determined by the objective criteria accompanying the rules of each competition, contest or game, for example skilfully piloting their vehicles to compete with other players in the Racing League, making strategic decisions, utilising their knowledge of game material, game mechanics, as well as the Kamigotchi ecosystem, or focusing their attention, experience and adroitness to achieve gameplay objectives.
        C. Participating in any game or contest available on the platform does not create any obligation on the Company to award any player with any earnings, prize or rewards. Rewards (if any) is entirely dependent on each player's skill as a player vis-a-vis other players in the relevant competition, contest or game.
        D. In the event that your usage of the App, Smart Contracts and the Site constitutes any form of gambling, betting, or wagering (howsoever named) under any laws applicable to you, you shall not be allowed to utilise the App, Smart Contracts and the Site.

    6. HEALTH AND SAFETY WARNINGS
The below information should be reviewed carefully before accessing the App. If the App will be accessed by children, this information should be read and explained to them by an adult. Failing to review the below health and safety precautions may cause damage to property, injury, or death. These health and safety precautions are not intended to be an exhaustive list, and use of the App may involve other health and/or safety risks not contained herein. The Company is not liable for any damage to property, injury, or death, including any of the foregoing that may occur as the result of your failure to review the health and safety precautions or as a result of your access to the App, or any interactions between you or your family members and people or objects in or around the play area (e.g. any collisions, tripping or injuries).
        A. Photosensitivity: Certain people may react to certain visual images or patterns, including flashing lights (regardless of whether they have a diagnosed condition or history). Reactions may be reduced by playing in a well-lit room, avoiding playing while drowsy, viewing the App from some distance or on a smaller screen, and limiting duration of use (do not access the App when tired or need sleep and take 10 or 15 minute breaks every 30 minutes while accessing the App). If you or anyone in your family has ever had symptoms related to epilepsy (seizures or loss of consciousness in particular) when exposed to flashing lights, you should consult your doctor prior to accessing the App. Parents and guardians should watch their children while accessing the App. Stop accessing the App immediately and consult a doctor if you or your child has any of the following symptoms: Eye or muscle twitching; Altered vision; Convulsions; Involuntary movements; Disorientation; or Loss of consciousness or awareness.
        B. Motion sickness: Playing video games (especially first-person or virtual reality games), including the App, may cause motion sickness in some players. If you or your child feels dizzy or nauseous when accessing the App, stop playing and rest. Do not drive, operate heavy machinery or engage in other demanding or strenuous activity until you feel better. To limit the risk of motion sickness while accessing the App, do not use the App when you are tired, need sleep, are under the influence of alcohol or drugs, are hung-over, have digestive problems, are under emotional stress or anxiety, or when suffering from cold, flu, headaches, migraines, or earaches or other health issues which may increase your susceptibility to adverse symptoms.
        C. Repetitive motion injuries and eyestrain: Playing video games, including the App, can make your muscles, joints, skin or eyes hurt. To avoid problems such as tendinitis, carpal tunnel syndrome, skin irritation or eyestrain, avoid excessive play, adults should monitor children, and take a 10 to 15 minute break every 30 minutes while accessing the App, in the event that your hands, wrists, arms, eyes or other parts of your body become tired or sore while playing, or if you feel symptoms such as tingling, numbness, burning or stiffness, do stop and rest for several hours before playing again.
        D. Children: Adults should monitor children who are accessing the App for any of the symptoms described below, and should limit the time children spend accessing the App and ensure that they take breaks during use. Prolonged use should be avoided, as it could negatively impact hand-eye coordination, balance, and multi-tasking ability. Adults should monitor children closely during and after use of the App for any decrease in these abilities.
        E. Most importantly, where you or your child exhibits any of the above symptoms or other discomfort during or after accessing the App, stop playing immediately and consult a doctor.

    7. ELIGIBILITY
You may only use the App, Smart Contracts and NFT if you comply with all of the following:
        A. You are at least eighteen (18) years old or otherwise of legal age to enter into an agreement as determined by the laws of the country/ territory where you live.
        B. You are not in violation of any law or regulation as a result of using the App, Smart Contracts or NFT. In this context, you agree that if you reside or are present in any jurisdiction that prohibits using the App, Smart Contracts and NFT (including without limitation any of the Restricted Territories (as defined therein)) you shall not utilise the App, Smart Contracts and NFT. Further, you will only use the App, Smart Contracts and NFT for your own personal use, and not on behalf of or for the benefit of any third party, and only in a manner that complies with all laws that apply to you.
        C. The App, Smart Contracts and NFT are intended only for users who are not prohibited by the laws of their country/territory from accessing the App, Smart Contracts or NFT. The Company does not intend to enable you to contravene any applicable law to you. You represent, warrant and agree to ensure that your use of the App, Smart Contracts and NFT will comply with all applicable laws, statutes and regulations applicable to you or those that are required to be complied with by you. The offering or availability of the App, Smart Contracts and NFT shall not be deemed or interpreted as an offer or invitation by us to use the App, Smart Contracts or NFT, if you reside in a place in which such use is currently forbidden by law (including without limitation the Restricted Territories), or where, the Company, in its sole discretion, elects not to offer the App, Smart Contracts or NFT. You shall be solely responsible for determining whether your use of the App, Smart Contracts and NFT is legal in the place where you live. We make no representations or warranties, express or implied, concerning the legality of the App, Smart Contracts or NFT and/or of any person’s use of the same, and shall not be responsible for any illegal use of the App, Smart Contracts and NFT by you. It is your responsibility to ensure that you comply with any and all laws applicable to you before using the App, Smart Contracts and NFT. If you have any doubts or concerns, you should consult with legal counsel in your country / territory about the legality of your use of the App, Smart Contracts and NFT. 
        D. You are not a resident of the United States of America, China, Afghanistan, Albania, American Samoa, Angola, Armenia, Azerbaijan, Belarus,  Bosnia, region of Balkans, Botswana, Burundi, Bosnia, Burma, Cambodia, Cameroon, Canada, Central African Republic, Chad, China, Côte D’Ivoire, Croatia, Crimea of Ukraine, Cuba, Democratic Republic of Congo, Democratic People’s Republic of Korea, Eritrea, Ethiopia, Ghana, Guam, Guinea, Guinea-Bissau, Haiti, Herzegovina, Iran, Iraq, Kosovo, Japan, Laos, Lebanon, Liberia, Libya, Madagascar, Mali, Macedonia, Mozambique, Myanmar, Nicaragua, Northern Mariana Islands, Pakistan, Moldova, Palestine, Puerto Rico, Russia, Serbia, Somalia, Sri Lanka, Sudan, South Sudan, Syrian Arab Republic, Tajikistan, Trinidad and Tobago, Turkmenistan, Uganda, Venezuela, Virgin Islands (U.S.), Yemen, or Zimbabwe ("Restricted Territories").
        E. The Company reserves the right to enforce geo-blocking of the App, Smart Contracts and NFT in the Restricted Territories. You must not use any software or networking techniques, including use of a VPN to modify your internet protocol address or otherwise circumvent or attempt to circumvent this prohibition. Notwithstanding the foregoing, the Company shall not be responsible for or be held liable for any contravention that may result from the access of the App, Smart Contracts and NFT from the Restricted Territories either through Virtual Private Network (VPN) or through any other means which allows users to access the same.

    8. OWNERSHIP; LICENSE; RESTRICTIONS
        A. For the purposes of this Section 8, the following capitalised terms will have the following meanings:
"Art" means any art, design, and drawings that may be associated with Kamigotchi or any NFT that you own.
"Third Party IP" means any third party patent rights (including, without limitation, patent applications and disclosures), copyrights, trade secrets, trademarks, know-how or any other intellectual property rights recognised in any country or jurisdiction in the world.
        B. Ownership
            i. You own the NFT. Each NFT is a digital record on the relevant Blockchain Network (as more described in the usage terms for the underlying intellectual property) which comprises, inter alia, a licence to display, modify and use the Art. When you purchase a NFT, you own the digital record on the relevant Blockchain Network completely. This means that you have the right to trade your NFT, sell it or give it away, and are fully responsible for all activities and interactions carried out in connection with such NFT. Ownership of each NFT is governed entirely by the Smart Contract and the relevant Blockchain Network.
            ii. The Company owns the App and the Site. You acknowledge and agree that the Company (or, as applicable, our licensors) owns and reserves all rights, title and interest in and to all elements of the App, and all intellectual property rights therein (including, without limitation, the Kamigotchi ecosystem, all designs, systems, methods, information, computer code, software, services, website design, "look and feel", themes, organisation, compilation of the content, code, data and database, functionality, audio, sound effects, video, animation, text, photograph, artwork, graphics, objects, characters, character  names, stories, dialogue, and all other elements of the App (collectively, the "Materials"). You acknowledge that the Materials are protected by copyright, trade dress, patent, and trademark laws, international conventions, other relevant intellectual property and proprietary rights, and applicable laws. All Materials are the copyrighted property of the Company or its licensors, and all trademarks, service marks, and trade names associated with the App or otherwise contained in the Materials are proprietary to the Company or its licensors. Except as expressly set forth herein, your use of the App does not grant you ownership of or any other rights with respect to any content, code, data, or other Materials that you may access on or through the App. We reserve all rights in and to the Materials that are not expressly granted to you in these Terms. For the sake of clarity, you understand and agree: (a) that your purchase of any NFT, whether via the App or otherwise, does not (save as described in the usage terms for the underlying intellectual property) give you any rights or licenses in or to the Materials other than those expressly contained in these Terms; and (b) that you will not apply for, register, or otherwise use or attempt to use any of the Company's trademarks or service marks, or any confusingly similar marks, anywhere in the world without our prior written consent in each case, which consent we may withhold at our sole and absolute discretion.
        C. Licence to utilise Art
Subject to your continued compliance with these Terms, the Company grants you a limited, non-exclusive, non-transferable, royalty-free license to utilise the Art (but not the Materials) for the following purposes:
            i. display the Art for you to access the Kamigotchi ecosystem, including paying of the game and as part of a marketplace that permits the purchase and sale of any NFT, provided that the marketplace cryptographically verifies each NFT owner’s rights to display the Art for the NFT to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the NFT is no longer listed for sale;
            ii. as part of a third party website or application that permits the inclusion, involvement, or participation of any NFT, provided that the website/application cryptographically verifies each NFT owner’s rights to display the Art for their NFT to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the NFT leaves the website/application;
            iii. to reproduce, distribute, display, perform, modify and create derivative works of the Art; and
            iv. commercialise any elements of the Art.
        D. Restrictions
You agree that you may not, nor permit any third party to do or attempt to do any of the foregoing without the Company's express prior written consent in each case:
            i. use the Art for Kamigotchi or your NFT to advertise, market, or sell any third party product or service;
            ii. use the Art for Kamigotchi or your NFT in connection with images, videos, or other forms of media that depict hatred, intolerance, violence, cruelty, or anything else that could reasonably be found to constitute hate speech or otherwise infringe upon the rights of others; or
            iii. attempt to trademark, copyright, or otherwise acquire additional intellectual property rights in or to the Art for Kamigotchi or your NFT.
To the extent that Art associated with Kamigotchi or your NFT contains Third Party IP (e.g., licensed intellectual property from a celebrity, athlete, or other public figure), you understand and agree as follows: (a) that you will not have the right to use such Third Party IP in any way except as incorporated in the Art, and subject to the license and restrictions contained herein; (b) that, depending on the nature of the license granted from the owner of the Third Party IP, the Company may need to pass through additional restrictions on your ability to use the Art; and (c) to the extent that the Company informs you of such additional restrictions in writing (email is permissible), you will be responsible for complying with all such restrictions from the date that you receive the notice, and that failure to do so will be deemed a breach of this license.
        E. User Generated Content
            i. The Company may provide features through the App that allow you to create, develop, modify, or contribute Content, including without limitation any username/name, images or graphics generated, or any interactions, messages, posts, comments or user generated content in any communication channel (including via the App, Twitter, Discord or Telegram), character data, buildings, in-game customisation and achievements, programs, gameplay, replays, cinematics, scripts experiences, interactive features, screenshots, music, sounds, sound recordings (and the musical works embodied therein), any audio-visual combinations, musical works, animations, and other types of works (standalone or in combination) ("UGC"), and to upload, publish, or otherwise make available UGC to some or all users of the App. These features may also allow you to interact with, manipulate, and change UGC in whole or in part. You may only use the tools that the Company provides through the normal functionality of the App to create, remove or modify UGC.
            ii. You accept and acknowledge that all UGC shall be considered non-confidential and non-proprietary information.
            iii. By creating UGC, you specifically grant the Company a perpetual, non-exclusive, irrevocable, transferable, sub-licensable, royalty-free, worldwide license to use, host, copy, duplicate, import, store, present, publicly display, publicly publish or perform (including by means of digital audio transmissions), modify, adapt, reproduce (and make mechanical reproductions of musical works embodied in sound recordings), create derivative works of (including synchronise to visual images), transfer, sub-license, distribute all or any part of the UGC to other users of the Services or any other third parties (including in particular and without limitation the right to authorise other users of the Services or third-parties to do the same); and the Company shall be free to use such UGC in any manner or media whatsoever, on an unrestricted basis and without any attribution or royalties or other compensation to you, including, without limitation, within or outside the Site or the App, or in any digital or printed media, including for any commercial publicity and marketing purposes. For the avoidance of doubt, the Company is not obligated to exercise any of the foregoing rights granted by you.
            iv. The Company does not allow intellectual-property infringement activities through the App or the services. You may not and agree not to create, generate, or make available any UGC to which you do not have the right to grant the Company the above licence in all of the elements of the UGC.
            v. You acknowledge that shall be solely responsible for any UGC that you choose to create, generate, submit, transmit or make available through the Site or the App, including your responsibility as to the legality, reliability, appropriateness, originality and copyright of any such information or material. Additionally, you represent and warrant that: (a) you are the creator and owner of, and own all right, title and interest in any UGC and/or have all the necessary licenses and rights to use and authorise the Company to exploit the above license granted to the Company in respect of UGC; (b) the Company does not need to obtain any further licenses, provide attribution, or pay royalties or other compensation to any third parties in connection with its usage of UGC; and (c) such UGC, and the Company's use of the UGC as contemplated under these Terms do not violate any applicable laws or regulations, nor will it infringe or violate any third-party rights, including copyright, trademark, patent, trade secret, moral rights, or the rights of privacy or publicity (and in particular it shall not comprise derogatory or criticising remarks regarding any person or entity or otherwise be defamatory in nature), nor will it violate any contractual arrangement between any party. You shall be solely liable for any damage resulting from any infringement or other violation of the copyright, trademarks or other proprietary rights of any individual or entity, and for any other harm or losses resulting from any UGC.
            vi. You may provide or otherwise publish or communicate to the Company or its agents any suggestions, comments, ideas, bug reports, and all other types of information or feedback, including software and code, directly or indirectly (including through your employees, agents, contractors, or representatives) relating to the App, including without limitation about how to improve the App (collectively, "Feedback"). By submitting any Feedback, you agree that we are free to use such Feedback at our discretion and without additional compensation to you, and to disclose such Feedback to third parties (whether on a non-confidential basis, or otherwise). You hereby grant the Company a perpetual, non-exclusive, fully paid, royalty-free, worldwide, irrevocable, sublicensable, transferable, and assignable license to use, reproduce, distribute, modify, adapt, prepare derivative works based on, publicly perform, publicly display, make, have made, use, sell, offer to sell, import, and otherwise exploit any and all Feedback for any purposes, for all current and future methods and forms of exploitation.
        F. The provisions in this Section 8 will survive the expiration or termination of these Terms.

    9. USER TERMS
        A. User Obligations
You agree that you are responsible for your own conduct while accessing or using the App, and for any consequences thereof. You agree to use the App, interact with other users, participate in any competitions, contests and games, utilise any modules, and/or create UGC only for purposes that are legal, proper and in accordance with these Terms and any applicable laws or regulations. By way of example, and not as a limitation, you may not, and may not allow any third party to:
            i. create, send, upload, distribute, disseminate, post, link to, advertise, promote or transmit anything that is unlawful, invasive of privacy, harmful, fraudulent, threatening, abusive, blasphemous, harassing, tortious, disparaging, defamatory, vulgar, sexually explicit, pornographic, paedophilic, libellous, obscene, relating to prohibited substances / drugs, hateful, racially or ethnically offensive, or relating to or encouraging money laundering or gambling, or otherwise objectionable;
            ii. distribute viruses, worms, defects, Trojan horses, corrupted files, hoaxes, or any other items of a destructive or deceptive nature;
            iii. impersonate another person (via the use of an email address or otherwise);
            iv. generate, upload, post, transmit or otherwise make available through the App any content that infringes the intellectual proprietary rights of any party;
            v. use the App to violate the legal rights (such as rights of privacy and publicity) of others;
            vi. engage in, promote, or encourage illegal activity (including, without limitation, money laundering);
            vii. interfere with other users' enjoyment of the App;
            viii. exploit the App for any unauthorised commercial purpose, or facilitate, create or maintain any unauthorised connection to the App or any aspect of the Kamigotchi ecosystem;
            ix. decompile, disassemble, reverse engineer, derive source code from, modify, alter, tamper with, repair, adapt, translate or otherwise create derivative works of any portion of the Site, the App, the Smart Contracts, the Materials, the Art (including without limitation unauthorized changes to the App client (“ini” file modification etc.), any underlying software, code, assets, graphics, gameplay mechanisms, online features servers, or data (such as packets) which affect or interfere with the App or the Services, or otherwise violate copyright laws;
            x. attempt to bypass any measure of the Site designed to prevent or restrict access to the Site, or any portion of the Site, the App and the Smart Contracts;
            xi. harass, intimidate, or threaten any of our employees or agents engaged in providing any portion of the Site, the App, and the Smart Contracts to you;
            xii. remove any copyright, trademark or other proprietary rights notices contained in or on the App or any part of it;
            xiii. reformat or frame any portion of the App;
            xiv. create, develop, distribute, or use any unauthorised software programs or technology that is not expressly authorised by the Company (including any third-party tools, mods, hacks, bots, skins, or any other software that alters the Site, the App, the Smart Contracts, the Materials, the Art in any way) in order to modify or interfere with the game experience, game function, or game visuals, or gain an advantage in any game mode;
            xv. display any content on the App that contains any hate-related or violent content or contains any other material, products or services that violate or encourage conduct that would violate any criminal laws, any other applicable laws, or any third party rights;
            xvi. use any robot, spider, site search/retrieval application, or other device to retrieve or index any portion of the App or the content posted on the App, or to collect information about its users for any unauthorised purpose;
            xvii. upload or transmit (or attempt to upload or to transmit) any material that acts as a passive or active information collection or transmission mechanism, including without limitation, clear graphics interchange formats (“gifs”), 1×1 pixels, web bugs, cookies, or other similar devices (sometimes referred to as “spyware” or “passive collection mechanisms” or “pcms”);
            xviii. engage in any automated use of the App, such as using scripts to send comments or messages, or using any data mining, robots, or similar data gathering and extraction tools, in each case whether or not any unfair advantage is obtained by the player;
            xix. access the App by automated means or under false or fraudulent pretences;
            xx. access or use the App for the purpose of creating a product or service that is competitive with any of our products or services;
            xxi. use the Site, the App and the Smart Contracts to advertise or offer to sell goods and services;
            xxii. disparage, tarnish, or otherwise harm, in our opinion, us and/or the Site, the App, and the Smart Contracts; or
            xxiii. engage in any practice that aims to manipulate the outcome of any competitions, contests, or games; all players should play to the best of their abilities and any sort of match-fixing, win-trading, or colluding between competitors is strictly prohibited.
If you engage in any of the activities prohibited by this Section 9, we may, at our sole and absolute discretion, without notice to you, and without limiting any of our other rights or remedies at law or in equity, immediately suspend or terminate your access to the App, the Site and/or the Smart Contracts and/or delete any UGC and/or images or descriptions associated with your NFT from the App and the Site.
        B. User Representations
By using the Site, the App, NFT and the Smart Contracts, you represent and warrant that:
            i. you have read and understood these Terms and all documentation on the App or the Site;
            ii. you have good and sufficient experience and understanding of the functionality, usage, storage, transmission mechanisms and other material characteristics of cryptographic tokens, token storage mechanisms (such as token wallets), blockchain technology, blockchain-like technology and blockchain-based software systems to understand these Terms and to appreciate the risks and implications of interacting with the App or creating or holding NFT;
            iii. you acknowledge and agree that we may impose eligibility criteria to access certain functionality in respect of the App or NFT which may require you to incur additional time and money costs;
            iv. you interact with the App, the Kamigotchi ecosystem, or create and own NFT for your own account, and shall not undertake the same on behalf of any other entity or person;
            v. your interaction with the App or creation and/or holding of NFT complies with applicable law and regulation in your jurisdiction, and the law and regulation of any jurisdiction to which you may be subject (including, but not limited to legal capacity and any other threshold requirements for interacting with the App or creation and/or holding of NFT, and interacting with other users within the App or the Kamigotchi ecosystem, and any applicable foreign exchange or regulatory restrictions or other governmental or other consents that may need to be obtained;
            vi. you have the legal capacity and you agree to comply with these Terms;
            vii. you will not use the Site, NFT, the App and the Smart Contracts for any illegal, immoral or unauthorised purpose;
            viii. you will not use the Site, NFT, the App and the Smart Contracts for any commercial purpose (save as approved by the Company in writing);
            ix. your use of the Site, NFT, the App and the Smart Contracts will not violate any applicable law or regulation; and
            x. any funds or digital assets used to interact with the App or creation and/or purchasing NFT are not derived from or related to any unlawful activities, including but not limited to money laundering or terrorist financing and all applicable statutes of all jurisdictions in which you are located, resident, organised or operating, and/or to which it may otherwise be subject and the rules and regulations thereunder (collectively, the "Compliance Regulations"), and you will not use the App or NFT to finance, engage in, or otherwise support any unlawful activities or in a manner which aids or facilitates another party in the same. To the extent required by applicable laws and regulations, you shall fully comply with all Compliance Regulations.
        C. Know Your Customer and Anti-Money Laundering
            i. The Company reserves the right to conduct "Know Your Customer" and "Anti-Money Laundering" checks on you if deemed necessary by the Company (at its sole discretion) or such checks become required under applicable laws in any jurisdiction.
            ii. Upon the Company's request, you shall immediately provide the Company with information and documents that the Company, in its sole discretion, deem necessary or appropriate to conduct "Know Your Customer" and "Anti-Money Laundering" checks. Such documents may include, but are not limited to, passports, driver's licenses, utility bills, photographs of associated individuals, government identification cards or sworn statements before notaries or other equivalent professionals.
            iii. Notwithstanding anything herein, the Company may, in its sole discretion, refuse to provide access to NFT, the Smart Contracts, the App or the Site to you until such requested information is provided, or in the event that, based on information available to the Company, you are suspected of using NFT, the Smart Contracts, the App or the Site in connection with any money laundering, terrorism financing, or any other illegal activity. In addition, the Company shall be entitled to use any possible efforts for preventing money laundering, terrorism financing or any other illegal activity, including without limitation blocking of your access to the App, the Site, or Smart Contracts, or providing your information to any regulatory authority.
        D. You are required to maintain and support the integrity and balance of the game (to be determined by the Company at its sole discretion) at all times, in order not to impact the enjoyment of the gameplay experience by other players. In particular, you are required to notify the Company of any glitches, exploits or vulnerability (such as bugs, system errors, illegal programs, etc.) in respect of the App or the Services, and must not exploit and/or propagate such information to other users. If you discover any glitches, exploits or vulnerability, do not disclose it to the Company and forward it to another person, this shall be deemed as a breach of these Terms.

    10. FEES AND PAYMENT
        A. If you elect to interact with the App or create or hold NFT (whether directly from us or in the peer-to-peer marketplace), any financial transactions that you engage in will be conducted solely through the relevant Blockchain Network. We will have no insight into or control over these payments or transactions, nor do we have the ability to reverse any transactions. With that in mind, we will have no liability to you or to any third party for any claims or damages that may arise as a result of any transactions that you engage in via the App, using the Smart Contracts, relating to NFT, or any other transactions that you conduct via the relevant Blockchain Network.
        B. The relevant Blockchain Network requires the payment of a transaction fee (a "Gas Fee") for every transaction that occurs on the relevant Blockchain Network. The Gas Fee funds the network of computers that run the decentralised network. This means that you will need to pay a Gas Fee for each transaction that occurs via the App.
        C. In addition to the Gas Fee, the App may charge a fee for participating in competitions, contests and games, usage of the App or underlying smart Contracts, or any trading activities in relation to NFT, as notified to you from time to time via the most updated fee schedule in the App or the Site (the "Transaction Fee"). For each transaction where a Transaction Fee is payable, we shall endeavour to provide you the opportunity to view and accept the Transaction Fee before confirming the transaction and paying the Transaction Fee. You acknowledge and agree that the Transaction Fee will be transferred directly to us through the relevant Blockchain Network as part of your payment. You must not pay, or attempt to pay, any Transaction Fee by fraudulent or unlawful means. 
        D. As between us, you will be solely responsible to pay any and all sales, use, value-added and other taxes, duties, and assessments (except taxes on our net income) now or hereafter claimed or imposed by any governmental authority (collectively, "Taxes") associated with your use of the App (including, without limitation, any Taxes that may become payable as the result of your ownership or transfer or interaction relating to the App or NFT). Except for income taxes levied on the Company, you:
            i. will pay or reimburse us for all national, federal, state, local or other taxes and assessments of any jurisdiction, including value added taxes and taxes as required by international tax treaties, customs or other import or export taxes, and amounts levied in lieu thereof based on charges set, services performed or payments made hereunder, as are now or hereafter may be imposed under the authority of any national, state, local or any other taxing jurisdiction; and
            ii. shall not be entitled to deduct the amount of any such taxes, duties or assessments from payments made to us pursuant to these Terms.

    11. LOSS OF DATA
In the event that any information or data relating to you or your use of the App, the Smart Contracts, Site, any element of the Kamigotchi gaming ecosystem, in-game digital resources, NFTs, or UGC, is lost, corrupted or otherwise no longer reasonably available or accessible (as determined by the Company in its sole discretion), you agree that to the greatest extent permissible at law the Company will have no liability to you of any nature relating to any such information or data.

    12. TERMINATION
        A. You may terminate these Terms at any time by discontinuing your access to the App and/or the Site.
        B. You agree that we, in our sole discretion and for any or no reason, may terminate these Terms and suspend and/or terminate your account(s) for the App. You agree that any suspension or termination of your access to the App may be without prior notice, and that we will not be liable to you or to any third party for any such suspension or termination. If we terminate these Terms or suspend or terminate your access to or use of the App due to your breach of these Terms or any suspected fraudulent, abusive, or illegal activity, then termination of these Terms will be in addition to any other remedies we may have at law or in equity.
        C. Sections 1C, 8, 9, 13, 14, 15 and 16 will survive the termination or expiration of these Terms for any reason.

    13. DISCLAIMERS
        A. YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR ACCESS TO AND USE OF THE APP AND NFT IS AT YOUR SOLE RISK; THE APP AND NFT IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, "WITH ALL FAULTS" AND WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, WE, OUR SUBSIDIARIES, AFFILIATES, AND LICENSORS MAKE NO EXPRESS WARRANTIES AND HEREBY DISCLAIM ALL IMPLIED WARRANTIES, CONDITIONS, COMMON LAW DUTIES, AND REPRESENTATIONS (EXPRESS, IMPLIED, ORAL, AND WRITTEN) REGARDING THE APP, NFT AND ANY PART OF IT, INCLUDING WITHOUT LIMITATION ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES AND CONDITIONS OF ANY KIND, SUCH AS TITLE, NON-INTERFERENCE WITH YOUR ENJOYMENT, AUTHORITY, NON-INFRINGEMENT, MERCHANTABILITY, FITNESS OR SUITABILITY FOR ANY PURPOSE (WHETHER OR NOT THE COMPANY KNOWS OR HAS REASON TO KNOW OF ANY SUCH PURPOSE), SYSTEM INTEGRATION, ACCURACY, COMPLETENESS, RELIABILITY, RESULTS, REASONABLE CARE, WORKMANLIKE EFFORT, LACK OF NEGLIGENCE, AND LACK OF VIRUSES, WHETHER ALLEGED TO ARISE UNDER LAW, BY REASON OF CUSTOM OR USAGE IN THE TRADE, OR BY COURSE OF DEALING. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, WE, OUR SUBSIDIARIES, AFFILIATES, AND LICENSORS DO NOT REPRESENT OR WARRANT TO YOU THAT: (I) YOUR ACCESS TO OR USE OF THE APP OR NFT WILL MEET YOUR REQUIREMENTS, (II) THE APP OR NFT WILL OPERATE PROPERTY OR YOUR ACCESS TO OR USE OF THE APP OR NFT WILL BE UNINTERRUPTED, TIMELY, SECURE, BUG FREE, OR ERROR FREE IN ANY OR ALL CIRCUMSTANCES, (III) THAT ANY DEFECTS IN THE APP OR NFT CAN OR WILL BE CORRECTED (IV) USAGE DATA PROVIDED THROUGH THE APP OR NFT WILL BE ACCURATE, (IV) THE NFT OR APP OR ANY CONTENT, SERVICES, OR FEATURES MADE AVAILABLE ON OR THROUGH THE APP ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR (V) THAT ANY DATA THAT YOU DISCLOSE WHEN YOU USE THE APP OR NFT WILL BE SECURE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES IN CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.
        B. YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND DEALING ONLINE OVER THE INTERNET, AND AGREE THAT WE HAVE NO LIABILITY OR RESPONSIBILITY FOR ANY BREACH OF SECURITY UNLESS IT IS DUE TO OUR WILFUL DEFAULT. In particular, you are aware and acknowledge that cyberthieves, scammers and other bad actors may attempt to impersonate the Company, takeover or hack the Site (and related domains) or the Company's social media accounts or in-game messaging tools, and/or other malicious activity, thereby providing you with malicious/scam website, links, information, announcements or call-to-action designed to fraudulently acquire your information, data, digital assets, digital wallet addresses or identity, or to falsify digital wallet address information in a manner designed to pay said bad actor instead of the Company; all the foregoing incidents may result in losses suffered by you and we have no liability or responsibility in respect of these actions of bad actors. You shall take all appropriate care to ensure that you check and verify with the Company or other independent sources any websites, links, information, announcements, call-to-actions, digital wallet addresses which you may come across in connection with the Kamigotchi game ecosystem.
        C. TO THE FULLEST EXTENT PERMISSIBLE BY LAW, WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSSES YOU INCUR AS THE RESULT OF YOUR USE OF THE RELEVANT BLOCKCHAIN NETWORK OR YOUR SELECTED ELECTRONIC WALLET, INCLUDING BUT NOT LIMITED TO ANY LOSSES, DAMAGES OR CLAIMS ARISING FROM: (i) USER ERROR, SUCH AS INCORRECTLY CONSTRUED SMART CONTRACTS OR OTHER TRANSACTIONS; (ii) SERVER FAILURE OR DATA LOSS; (iii) CORRUPTED WALLET FILES; OR (iv) UNAUTHORISED ACCESS OR ACTIVITIES BY THIRD PARTIES, INCLUDING BUT NOT LIMITED TO THE USE OF VIRUSES, PHISHING, BRUTEFORCING OR OTHER MEANS OF ATTACK AGAINST THE APP OR NFT, THE RELEVANT BLOCKCHAIN NETWORK, OR YOUR SELECTED ELECTRONIC WALLET.
        D. NFTS ARE INTANGIBLE DIGITAL ASSETS THAT EXIST ONLY BY VIRTUE OF THE OWNERSHIP RECORD MAINTAINED IN THE RELEVANT BLOCKCHAIN NETWORK. ALL SMART CONTRACTS IN CONNECTION WITH THE KAMIGOTCHI ECOSYSTEM ARE DEPLOYED ON AND INTERACTIONS/TRANSACTIONS WITH THE SAME OCCUR ON THE DECENTRALISED LEDGER WITHIN THE RELEVANT BLOCKCHAIN NETWORK. WE HAVE NO CONTROL OVER AND MAKE NO GUARANTEES OR PROMISES WITH RESPECT TO SMART CONTRACTS.
        E. THE COMPANY IS NOT RESPONSIBLE FOR LOSSES DUE TO BLOCKCHAINS OR ANY OTHER FEATURES OF THE RELEVANT BLOCKCHAIN NETWORK OR YOUR SELECTED ELECTRONIC WALLET, INCLUDING BUT NOT LIMITED TO LATE REPORT BY DEVELOPERS OR REPRESENTATIVES (OR NO REPORT AT ALL) OF ANY ISSUES WITH THE BLOCKCHAIN SUPPORTING THE RELEVANT BLOCKCHAIN NETWORK, INCLUDING FORKS, TECHNICAL NODE ISSUES, OR ANY OTHER ISSUES HAVING FUND LOSSES AS A RESULT.
    14. LIMITATION OF LIABILITY
        A. TO THE FULLEST EXTENT PERMISSIBLE BY LAW, YOU UNDERSTAND AND AGREE THAT THE COMPANY, ITS SUBSIDIARIES, AFFILIATES, SERVICE PROVIDERS AND LICENSORS (THE "COMPANY PARTIES") WILL NOT BE LIABLE IN ANY WAY TO YOU OR TO ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES WHICH YOU MAY INCUR IN CONNECTION WITH THESE TERMS OR YOUR ACCESS TO OR USE OF (OR YOUR INABILITY TO ACCESS OR USE) ANY PORTION OF THE APP OR NFT, HOWSOEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, INCLUDING, WITHOUT LIMITATION, ANY LOSS OF PROFITS (WHETHER INCURRED DIRECTLY OR INDIRECTLY), LOSS OF GOODWILL OR BUSINESS REPUTATION, LOSS OF DATA, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR ANY OTHER INTANGIBLE LOSS, EVEN IF THE COMPANY PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND EVEN IN THE EVENT OF ANY COMPANY PARTY'S FAULT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, INDEMNITY, PRODUCT LIABILITY, BREACH OF CONTRACT, BREACH OF WARRANTY, OR OTHERWISE.
        B. FURTHER, TO THE FULLEST EXTENT PERMISSIBLE BY LAW, YOU AGREE THAT THE TOTAL, AGGREGATE LIABILITY OF THE COMPANY PARTIES TO YOU FOR ANY AND ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR ACCESS TO OR USE OF (OR YOUR INABILITY TO ACCESS OR USE) ANY PORTION OF THE APP OR NFT, WHETHER IN CONTRACT, TORT, STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, IS LIMITED TO THE GREATER OF (I) THE AMOUNTS YOU ACTUALLY PAY TO THE COMPANY IN THE 12 MONTH PERIOD PRECEDING THE EVENTS GIVING RISE TO SUCH LIABILITY, OR (II) US$200. THESE LIMITATIONS AND EXCLUSIONS REGARDING DAMAGES APPLY EVEN IF ANY REMEDY FAILS TO PROVIDE ADEQUATE COMPENSATION.
        C. YOU ACKNOWLEDGE AND AGREE THAT THE COMPANY HAS MADE THE APP AND NFT AVAILABLE TO YOU AND ENTERED INTO THESE TERMS IN RELIANCE UPON THE WARRANTY DISCLAIMERS AND LIMITATIONS OF LIABILITY SET FORTH HEREIN, WHICH REFLECT A REASONABLE AND FAIR ALLOCATION OF RISK BETWEEN THE PARTIES AND FORM AN ESSENTIAL BASIS OF THE BARGAIN BETWEEN YOU AND THE COMPANY. THE COMPANY WOULD NOT BE ABLE TO PROVIDE THE APP AND NFT TO YOU WITHOUT THESE LIMITATIONS.
        D. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, AND SOME JURISDICTIONS ALSO LIMIT DISCLAIMERS OR LIMITATIONS OF LIABILITY FOR PERSONAL INJURY FROM CONSUMER PRODUCTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO PERSONAL INJURY CLAIMS.
    15. ASSUMPTION OF RISK
You accept and acknowledge each of the following:
        A. The prices of blockchain assets are extremely volatile. Fluctuations in the price of other digital assets could materially and adversely affect the value of your NFT, which may also be subject to significant price volatility. We cannot guarantee that any purchasers of NFT will not lose money.
        B. You are solely responsible for determining what, if any, taxes apply to your interaction relating to the App or NFT. The Company is not responsible for determining the taxes that apply to your transactions on the App, the Site, or the Smart Contracts.
        C. The App does not store, send, or receive NFT. This is because NFT exist only by virtue of the ownership record maintained on the App’s supporting blockchain in the relevant Blockchain Network. Any transfer of NFT occurs within the supporting blockchain in the relevant Blockchain Network, and not on the App.
        D. The App and any publicly deployed Smart Contracts you interact with may contain security vulnerabilities, errors, failures, bugs or economic loopholes which may be exploited by third parties. Interaction with the App and Smart Contracts are entirely your own responsibility and liability.
        E. At any time, your access to the App, NFT or any digital assets, may be suspended or terminated or there may be a delay in your access or use of your digital assets, which may result in the NFT or digital assets diminishing in value or you being unable to interact with a Smart Contract, the App or the Site. The App or the Site may be suspended or terminated for any or no reason, which may limit your access to your digital assets.
        F. There are risks associated with using an Internet-based currency, including, but not limited to, the risk of hardware, software and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorised access to information stored within your account or wallet. You accept and acknowledge that the Company will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience in connection with the App, the Smart Contracts, NFT or when using the relevant Blockchain Network, however caused.
        G. Because the App and NFT is based on blockchain technology, any malfunction, breakdown or abandonment of the relevant Blockchain Network may have a material adverse effect on the App or any NFT you own. Moreover, advances in cryptography, or technical advances such as the development of quantum computing, could present risks to the App or NFT, any underlying digital assets, or the relevant Blockchain Network by rendering ineffective the cryptographic consensus mechanism that underpins the relevant Blockchain Network. The future of cryptography and security innovations are highly unpredictable.
        H. A private key, or a combination of private keys, is necessary to control and dispose of NFT stored in your digital wallet, vault or other storage mechanism. Accordingly, loss of requisite private key(s) associated with such digital wallet, vault or other storage mechanism storing NFT may result in loss of such NFT. Moreover, any third party that gains access to such private key(s), including by gaining access to login credentials, may be able to misappropriate any NFT held by you. The Company cannot be responsible for any such losses.
        I. Hackers or other malicious groups or organisations may attempt to interfere with the App, the Smart Contracts, the Site or NFT in a variety of ways, including, but not limited to, malware attacks, denial of service attacks, consensus-based attacks, Sybil attacks, smurfing and spoofing, which may result in losses incurred by you.
        J. A lack of use or public interest in the creation and development of distributed ecosystems could negatively impact the development of the Kamigotchi ecosystem, and therefore the potential utility or value of the App or NFT.
        K. The regulatory regime governing blockchain technologies, digital assets and tokens is uncertain, and new regulations or policies may materially adversely affect the development of the Kamigotchi ecosystem, and therefore the potential utility or value of the App or NFT.
        L. An upgrade, hard fork, or a change in how transactions are confirmed on the relevant Blockchain Network may have unintended, adverse effects on all applications deployed on that blockchain network, including Kamigotchi.
        M. Blockchain-based applications and cryptographic tokens such as the App or NFT are a new and untested technology. In addition to the aforementioned risks, there may be other risks associated with your interaction with the App and holding or use of NFT, including those that the Company cannot anticipate. Such risks may further materialise as unanticipated variations or combinations of the risks discussed herein.

    16. INDEMNIFICATION
        A. TO THE FULLEST EXTENT PERMISSIBLE BY LAW, YOU AGREE TO HOLD HARMLESS AND INDEMNIFY THE COMPANY PARTIES FROM AND AGAINST ANY CLAIM, DEMAND, LIABILITY, LOSS, DAMAGE (ACTUAL AND CONSEQUENTIAL) OF ANY KIND OR NATURE, EXPENSE, ACTION SUIT, JUDGMENT, LITIGATION COST, AND ATTORNEYS' FEES, COSTS AND EXPERT WITNESS' FEES ARISING OUT OF OR IN ANY WAY RELATED TO (I) ANY CLAIM THAT, IF TRUE, WOULD CONSTITUTE A BREACH BY YOU OF THESE TERMS, (II) ANY ACT OR OMISSION BY YOU IN USING THE APP OR NFT, (III) YOUR VIOLATION OF APPLICABLE LAWS, RULES OR REGULATIONS IN CONNECTION WITH YOUR ACCESS TO OR USE OF THE APP OR NFT, OR (IV) ANY CLAIM OF INFRINGEMENT OR VIOLATION OF ANY THIRD-PARTY INTELLECTUAL PROPERTY RIGHTS ARISING FROM THE COMPANY'S USE OF YOUR UGC OR FEEDBACK AS PROVIDED IN THESE TERMS.
        B. You agree to reimburse the Company on demand for any defence costs incurred by any Company Party and any payments made or loss suffered by any Company Party, whether in a court judgment or settlement, based on any matter covered by this Section 16.
        C. You agree that the Company will have control of the defence or settlement of any claims relating to this Section 16.

    17. EXTERNAL WEBSITES AND SERVICES
        A. The App may offer you the option to access other websites or resources, in particular third party websites, software, services, advertisements or third-party materials (collectively, "External Services"), which are provided solely as a convenience to users. 
        B. The Company has no control over any External Services. Prior to accessing any External Services, you should carefully read any applicable terms and conditions, privacy policies and any relevant documentation relating to such External Services.
        C. You acknowledge and agree that the Company is not responsible for the availability of any External Services or your interactions with them, and that the Company does not endorse any information, advertising, products or other materials on or made available from any External Services.
        D. Furthermore, you acknowledge and agree that the Company is not liable for any loss or damage which may be incurred as a result of your usage of or the availability or unavailability of the External Services, or as a result of any reliance placed by you upon the completeness, accuracy or existence of any information advertising, products or other materials on, or made available from, any External Services.

    18. CHANGES TO THE APP
We are constantly innovating the App to help provide the best possible experience. You acknowledge and agree that the form and nature of the App, and any part of it, may change from time to time without prior notice to you, and that we may add new features and change any part of the App at any time without notice.

    19. PRIVACY POLICY AND USER DATA
        A. Our Privacy Policy (available at [link]) describes the ways we collect, use, store and disclose your personal information, and is hereby incorporated by this reference into these Terms. You agree to the collection, use, storage, and disclosure of your data in accordance with the aforementioned Privacy Policy.
        B. We will maintain certain data that you transmit to the Site, the App and the Smart Contracts for the purpose of managing the performance of the Site, the App and the Smart Contracts, as well as data relating to your use of the Site, the App and the Smart Contracts. Although we perform regular routine backups of data, you are solely responsible for all data that you transmit or that relate to any activity you have undertaken using the Site, the App and the Smart Contracts. You agree that we shall have no liability to you for any loss or corruption of any such data, and you hereby waive any right of action against us arising from any such loss or corruption of such data.

    20. GOVERNING LAW AND DISPUTE RESOLUTION (ARBITRATION)
        A. Please read this Section 20 carefully. It requires you to arbitrate disputes with the Company, and limits the manner in which you can seek relief from the Company.
        B. These Terms and your use access to and use of the Services will be governed by and construed in accordance with the laws of the British Virgin Islands, without regard to conflict of law rules and principles (whether of the British Virgin Islands or any other jurisdiction) that would cause the application of the laws of any other jurisdiction.
        C. All disputes arising out of or in connection with these Terms (including without limitation the enforceability of this Section 20 or any question regarding its existence, validity or termination, your access or use of the App, the Site, or the Smart Contracts, or to any products sold or distributed through the App, the Site, or the Smart Contracts) shall be referred to and finally resolved by arbitration administered by the British Virgin Islands International Arbitration Centre in accordance with its procedural rules for the time being in force. The tribunal shall consist of 1 arbitrator, who shall have exclusive authority to decide all issues relating to the interpretation, applicability, enforceability and scope of this arbitration agreement. The language used in the arbitral proceedings shall be English. Each Party irrevocably submits to the jurisdiction and venue of such tribunal. Each party will cover its own fees and costs associated with the arbitration proceedings. Notwithstanding the foregoing, the Company may seek and obtain injunctive relief in any jurisdiction in any court of competent jurisdiction, and you agree that these Terms are specifically enforceable by the Company through injunctive relief and other equitable remedies without proof of monetary damages.
        D. WITH RESPECT TO ANY DISPUTE ARISING OUT OF OR RELATED TO THESE TERMS, INCLUDING WITHOUT LIMITATION DISPUTES RELATED TO THE APP, THE SITE, THE SMART CONTRACTS, OR ANY PRODUCTS SOLD OR DISTRIBUTED THROUGH THE APP, THE SITE, OR THE SMART CONTRACTS: (I) YOU HEREBY EXPRESSLY GIVE UP YOUR RIGHT TO HAVE A TRIAL BY JURY; AND (II) YOU HEREBY EXPRESSLY GIVE UP YOUR RIGHT TO PARTICIPATE AS A MEMBER OF A CLASS OF CLAIMANTS IN ANY LAWSUIT, INCLUDING BUT NOT LIMITED TO CLASS ACTION LAWSUITS INVOLVING ANY SUCH DISPUTE.

    21. GENERAL
        A. These Terms and any document or information referred to in these Terms or incorporated by reference constitute the entire agreement between you and the Company relating to the subject matter(s) covered by these Terms. All other communications, proposals, and representations with respect to the same subject matter(s), whether written or oral, whether occurring prior, contemporaneously or after, are expressly excluded.
        B. There are no third party beneficiaries to these Terms. A person who is not a party under these Terms has no right under any laws to enforce or to enjoy the benefit of these Terms.
        C. The parties are independent of each other, and nothing in these Terms create any agency, partnership, joint venture or any similar relationship, nor cause the parties to be deemed acting in concert in any respect.
        D. The original of these Terms shall be in English; and any translations are provided for reference purposes only. In the event of conflict or ambiguity between the English language version and translated versions of these Terms, the English language versions shall prevail. You acknowledge that you have read and understood the English language version of these Terms, and you waive any right you may have under the law of your country to have these Terms written or construed in the language of any other country.
        E. The language in these Terms will be interpreted as to its fair meaning, and not strictly for or against any party.
        F. You may not assign, transfer, charge or sub-contract any or your rights or obligations under these Terms, whether by operation of law or otherwise, without the Company's prior written consent; any attempt to effect the foregoing without such consent will be null and void. Notwithstanding anything contained herein, the Company may assign, transfer, charge or sub-contract all or any of its rights and obligations under these Terms in its sole discretion (without your consent) to an affiliate for any reason, including without limitation any assignment or novation in connection with a reincorporation to change the Company's domicile.
        G. Should any provision or part-provision of these Terms is or becomes invalid, illegal or unenforceable in any respect under any law of any jurisdiction, it shall be deemed modified to the minimum extent necessary to make it valid, legal and enforceable; if such modification is not possible, the relevant provision or part-provision shall be deemed deleted. Any modification to or deletion of a provision or part-provision pursuant to this Section 21G shall not affect or impair the validity and enforceability of the rest of these Terms, nor the validity and enforceability of such provision or part-provision under the law of any other jurisdiction.
        H. Any act by the Company to exercise, or failure or delay in exercise of, any of its rights under these Terms, at law or in equity, will not be deemed a waiver of those or any other rights or remedies available in contract, at law or in equity.
        I. The Company will not be liable for any failure or delayed performance of its obligations that result from any condition beyond its reasonable control, including, but not limited to, governmental action, acts of terrorism, earthquake, fire, flood, acts of God, labour conditions, power failures, Internet disturbances, or acts or omissions of third parties.
        J. You agree that we may provide you with notices (including, without limitation those regarding changes to these Terms) by email, regular mail, or postings on the App. By providing us with your email address, you consent to our using the email address to send you any notices required by law in lieu of communication by postal mail.

Last Updated: 5 May 2025
`,
];
