// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v5.29.3
// source: middleware.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "middleware";

export interface ECSEvent {
  eventType: string;
  componentId: string;
  entityId: string;
  value?: Uint8Array | undefined;
  txHash: string;
}

/** Replies */
export interface StreamResponse {
  blockNumber: number;
  ecsEvents: ECSEvent[];
  logIndex: number;
  prevLogBlockNumber: number;
  prevLogIndex: number;
}

export interface MWResponse {
  entityIds: string[];
  componentIds: string[];
  events: ECSEvent[];
}

export interface ComponentValue {
  componentId: string;
  value: Uint8Array;
}

export interface EntityComponents {
  entityId: string;
  components: ComponentValue[];
  children: EntityComponents[];
}

export interface GetComponentValuesRequest {
  entityId: string;
  key: string;
  includeChildren: boolean;
}

export interface GetComponentValuesResponse {
  entity: EntityComponents | undefined;
}

export interface GetComponentValuesByTypeRequest {
  key: string;
  includeChildren: boolean;
}

export interface GetComponentValuesByTypeResponse {
  entities: EntityComponents[];
}

/** Requests */
export interface StreamRequest {
}

function createBaseECSEvent(): ECSEvent {
  return { eventType: "", componentId: "", entityId: "", value: undefined, txHash: "" };
}

export const ECSEvent: MessageFns<ECSEvent> = {
  encode(message: ECSEvent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.eventType !== "") {
      writer.uint32(10).string(message.eventType);
    }
    if (message.componentId !== "") {
      writer.uint32(18).string(message.componentId);
    }
    if (message.entityId !== "") {
      writer.uint32(26).string(message.entityId);
    }
    if (message.value !== undefined) {
      writer.uint32(34).bytes(message.value);
    }
    if (message.txHash !== "") {
      writer.uint32(42).string(message.txHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ECSEvent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseECSEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.eventType = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.componentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.entityId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.value = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.txHash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ECSEvent>): ECSEvent {
    return ECSEvent.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ECSEvent>): ECSEvent {
    const message = createBaseECSEvent();
    message.eventType = object.eventType ?? "";
    message.componentId = object.componentId ?? "";
    message.entityId = object.entityId ?? "";
    message.value = object.value ?? undefined;
    message.txHash = object.txHash ?? "";
    return message;
  },
};

function createBaseStreamResponse(): StreamResponse {
  return { blockNumber: 0, ecsEvents: [], logIndex: 0, prevLogBlockNumber: 0, prevLogIndex: 0 };
}

export const StreamResponse: MessageFns<StreamResponse> = {
  encode(message: StreamResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.blockNumber !== 0) {
      writer.uint32(8).uint32(message.blockNumber);
    }
    for (const v of message.ecsEvents) {
      ECSEvent.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.logIndex !== 0) {
      writer.uint32(48).uint32(message.logIndex);
    }
    if (message.prevLogBlockNumber !== 0) {
      writer.uint32(64).uint32(message.prevLogBlockNumber);
    }
    if (message.prevLogIndex !== 0) {
      writer.uint32(72).uint32(message.prevLogIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.blockNumber = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.ecsEvents.push(ECSEvent.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.logIndex = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.prevLogBlockNumber = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.prevLogIndex = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<StreamResponse>): StreamResponse {
    return StreamResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StreamResponse>): StreamResponse {
    const message = createBaseStreamResponse();
    message.blockNumber = object.blockNumber ?? 0;
    message.ecsEvents = object.ecsEvents?.map((e) => ECSEvent.fromPartial(e)) || [];
    message.logIndex = object.logIndex ?? 0;
    message.prevLogBlockNumber = object.prevLogBlockNumber ?? 0;
    message.prevLogIndex = object.prevLogIndex ?? 0;
    return message;
  },
};

function createBaseMWResponse(): MWResponse {
  return { entityIds: [], componentIds: [], events: [] };
}

export const MWResponse: MessageFns<MWResponse> = {
  encode(message: MWResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entityIds) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.componentIds) {
      writer.uint32(18).string(v!);
    }
    for (const v of message.events) {
      ECSEvent.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MWResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMWResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entityIds.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.componentIds.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.events.push(ECSEvent.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<MWResponse>): MWResponse {
    return MWResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MWResponse>): MWResponse {
    const message = createBaseMWResponse();
    message.entityIds = object.entityIds?.map((e) => e) || [];
    message.componentIds = object.componentIds?.map((e) => e) || [];
    message.events = object.events?.map((e) => ECSEvent.fromPartial(e)) || [];
    return message;
  },
};

function createBaseComponentValue(): ComponentValue {
  return { componentId: "", value: new Uint8Array(0) };
}

export const ComponentValue: MessageFns<ComponentValue> = {
  encode(message: ComponentValue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.componentId !== "") {
      writer.uint32(10).string(message.componentId);
    }
    if (message.value.length !== 0) {
      writer.uint32(18).bytes(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ComponentValue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComponentValue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.componentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ComponentValue>): ComponentValue {
    return ComponentValue.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ComponentValue>): ComponentValue {
    const message = createBaseComponentValue();
    message.componentId = object.componentId ?? "";
    message.value = object.value ?? new Uint8Array(0);
    return message;
  },
};

function createBaseEntityComponents(): EntityComponents {
  return { entityId: "", components: [], children: [] };
}

export const EntityComponents: MessageFns<EntityComponents> = {
  encode(message: EntityComponents, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entityId !== "") {
      writer.uint32(10).string(message.entityId);
    }
    for (const v of message.components) {
      ComponentValue.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.children) {
      EntityComponents.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EntityComponents {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntityComponents();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entityId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.components.push(ComponentValue.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.children.push(EntityComponents.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<EntityComponents>): EntityComponents {
    return EntityComponents.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EntityComponents>): EntityComponents {
    const message = createBaseEntityComponents();
    message.entityId = object.entityId ?? "";
    message.components = object.components?.map((e) => ComponentValue.fromPartial(e)) || [];
    message.children = object.children?.map((e) => EntityComponents.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetComponentValuesRequest(): GetComponentValuesRequest {
  return { entityId: "", key: "", includeChildren: false };
}

export const GetComponentValuesRequest: MessageFns<GetComponentValuesRequest> = {
  encode(message: GetComponentValuesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entityId !== "") {
      writer.uint32(10).string(message.entityId);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    if (message.includeChildren !== false) {
      writer.uint32(24).bool(message.includeChildren);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetComponentValuesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetComponentValuesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entityId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.includeChildren = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetComponentValuesRequest>): GetComponentValuesRequest {
    return GetComponentValuesRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetComponentValuesRequest>): GetComponentValuesRequest {
    const message = createBaseGetComponentValuesRequest();
    message.entityId = object.entityId ?? "";
    message.key = object.key ?? "";
    message.includeChildren = object.includeChildren ?? false;
    return message;
  },
};

function createBaseGetComponentValuesResponse(): GetComponentValuesResponse {
  return { entity: undefined };
}

export const GetComponentValuesResponse: MessageFns<GetComponentValuesResponse> = {
  encode(message: GetComponentValuesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entity !== undefined) {
      EntityComponents.encode(message.entity, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetComponentValuesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetComponentValuesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entity = EntityComponents.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetComponentValuesResponse>): GetComponentValuesResponse {
    return GetComponentValuesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetComponentValuesResponse>): GetComponentValuesResponse {
    const message = createBaseGetComponentValuesResponse();
    message.entity = (object.entity !== undefined && object.entity !== null)
      ? EntityComponents.fromPartial(object.entity)
      : undefined;
    return message;
  },
};

function createBaseGetComponentValuesByTypeRequest(): GetComponentValuesByTypeRequest {
  return { key: "", includeChildren: false };
}

export const GetComponentValuesByTypeRequest: MessageFns<GetComponentValuesByTypeRequest> = {
  encode(message: GetComponentValuesByTypeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.includeChildren !== false) {
      writer.uint32(24).bool(message.includeChildren);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetComponentValuesByTypeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetComponentValuesByTypeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.includeChildren = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetComponentValuesByTypeRequest>): GetComponentValuesByTypeRequest {
    return GetComponentValuesByTypeRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetComponentValuesByTypeRequest>): GetComponentValuesByTypeRequest {
    const message = createBaseGetComponentValuesByTypeRequest();
    message.key = object.key ?? "";
    message.includeChildren = object.includeChildren ?? false;
    return message;
  },
};

function createBaseGetComponentValuesByTypeResponse(): GetComponentValuesByTypeResponse {
  return { entities: [] };
}

export const GetComponentValuesByTypeResponse: MessageFns<GetComponentValuesByTypeResponse> = {
  encode(message: GetComponentValuesByTypeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entities) {
      EntityComponents.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetComponentValuesByTypeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetComponentValuesByTypeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entities.push(EntityComponents.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetComponentValuesByTypeResponse>): GetComponentValuesByTypeResponse {
    return GetComponentValuesByTypeResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetComponentValuesByTypeResponse>): GetComponentValuesByTypeResponse {
    const message = createBaseGetComponentValuesByTypeResponse();
    message.entities = object.entities?.map((e) => EntityComponents.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStreamRequest(): StreamRequest {
  return {};
}

export const StreamRequest: MessageFns<StreamRequest> = {
  encode(_: StreamRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<StreamRequest>): StreamRequest {
    return StreamRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<StreamRequest>): StreamRequest {
    const message = createBaseStreamRequest();
    return message;
  },
};

export type MiddlewareServiceDefinition = typeof MiddlewareServiceDefinition;
export const MiddlewareServiceDefinition = {
  name: "MiddlewareService",
  fullName: "middleware.MiddlewareService",
  methods: {
    /** Stream */
    subscribeToStream: {
      name: "SubscribeToStream",
      requestType: StreamRequest,
      requestStream: false,
      responseType: StreamResponse,
      responseStream: true,
      options: {},
    },
    getComponentValues: {
      name: "GetComponentValues",
      requestType: GetComponentValuesRequest,
      requestStream: false,
      responseType: GetComponentValuesResponse,
      responseStream: false,
      options: {},
    },
    getComponentValuesByType: {
      name: "GetComponentValuesByType",
      requestType: GetComponentValuesByTypeRequest,
      requestStream: false,
      responseType: GetComponentValuesByTypeResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface MiddlewareServiceImplementation<CallContextExt = {}> {
  /** Stream */
  subscribeToStream(
    request: StreamRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<StreamResponse>>;
  getComponentValues(
    request: GetComponentValuesRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetComponentValuesResponse>>;
  getComponentValuesByType(
    request: GetComponentValuesByTypeRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<GetComponentValuesByTypeResponse>>;
}

export interface MiddlewareServiceClient<CallOptionsExt = {}> {
  /** Stream */
  subscribeToStream(
    request: DeepPartial<StreamRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<StreamResponse>;
  getComponentValues(
    request: DeepPartial<GetComponentValuesRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetComponentValuesResponse>;
  getComponentValuesByType(
    request: DeepPartial<GetComponentValuesByTypeRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<GetComponentValuesByTypeResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
