import { cdnAudio } from './constants';
import type { AudioRegistry } from './types';

const registry: AudioRegistry = {
  master: { volume: 0.8 },
  buses: {
    bgm: { volume: 0.6 },
    fx: { volume: 0.7, duckBgmByDb: 6, duckAttackMs: 10, duckReleaseMs: 250 },
  },
  assets: [
    {
      key: 'bgm.cave',
      src: cdnAudio('sound/ost/cave'),
      bus: 'bgm',
      chain: 'presets/warm-room.json',
      loop: true,
      preload: true,
      volume: 1.0,
    },
    {
      key: 'fx.click',
      src: cdnAudio('sound/fx/interaction/click'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 6,
      cooldownMs: 15,
      volume: 0.9,
    },
    {
      key: 'fx.fund',
      src: cdnAudio('sound/fx/interaction/fund'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 10,
      volume: 0.9,
    },
    {
      key: 'fx.scribble',
      src: cdnAudio('sound/fx/interaction/scribble'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 10,
      volume: 0.9,
    },
    {
      key: 'fx.signup',
      src: cdnAudio('sound/fx/interaction/signup'),
      bus: 'fx',
      chain: 'presets/success-sparkle.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 10,
      volume: 1.0,
    },
    {
      key: 'fx.success',
      src: cdnAudio('sound/fx/interaction/success'),
      bus: 'fx',
      chain: 'presets/success-sparkle.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 50,
      volume: 1.0,
    },
    {
      key: 'fx.vend',
      src: cdnAudio('sound/fx/interaction/vend'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 2,
      cooldownMs: 50,
      volume: 1.0,
    },
    {
      key: 'fx.message',
      src: cdnAudio('sound/fx/interaction/message'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 25,
      volume: 0.9,
    },
  ],
};

export default registry;
