import { cdnAudio } from './constants';
import type { AudioRegistry } from './types';

const registry: AudioRegistry = {
  master: { volume: 0.8 },
  buses: {
    bgm: { volume: 0.6 },
    fx: { volume: 0.7, duckBgmByDb: 6, duckAttackMs: 10, duckReleaseMs: 250 },
  },
  assets: [
    {
      key: 'bgm.cave',
      src: cdnAudio('sound/ost/cave', 'mp3'),
      bus: 'bgm',
      chain: 'presets/warm-room.json',
      loop: true,
      preload: true,
      volume: 1.0,
    },
    {
      key: 'fx.bell',
      src: cdnAudio('sound/fx/interaction/bell', 'mp3'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 10,
      volume: 0.9,
    },
    {
      key: 'fx.click',
      src: cdnAudio('sound/fx/interaction/click2', 'mp3'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 6,
      cooldownMs: 15,
      volume: 0.9,
    },
    {
      key: 'fx.crafting',
      src: cdnAudio('sound/fx/interaction/crafting', 'mp3'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 100,
      volume: 0.9,
    },
    {
      key: 'fx.error',
      src: cdnAudio('sound/fx/interaction/error', 'mp3'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 25,
      volume: 0.9,
    },
    {
      key: 'fx.fund',
      src: cdnAudio('sound/fx/interaction/fund', 'mp3'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 10,
      volume: 0.9,
    },
    {
      key: 'fx.levelup',
      src: cdnAudio('sound/fx/interaction/levelup', 'mp3'),
      bus: 'fx',
      chain: 'presets/success-sparkle.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 100,
      volume: 1.0,
    },
    {
      key: 'fx.liquidate',
      src: cdnAudio('sound/fx/interaction/liquidate', 'mp3'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 50,
      volume: 0.9,
    },
    {
      key: 'fx.message',
      src: cdnAudio('sound/fx/interaction/message', 'mp3'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 25,
      volume: 0.9,
    },
    {
      key: 'fx.questaccept',
      src: cdnAudio('sound/fx/interaction/questaccept', 'mp3'),
      bus: 'fx',
      chain: 'presets/success-sparkle.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 50,
      volume: 1.0,
    },
    {
      key: 'fx.questcomplete',
      src: cdnAudio('sound/fx/interaction/questcomplete', 'mp3'),
      bus: 'fx',
      chain: 'presets/success-sparkle.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 50,
      volume: 1.0,
    },
    {
      key: 'fx.revive',
      src: cdnAudio('sound/fx/interaction/revive', 'mp3'),
      bus: 'fx',
      chain: 'presets/success-sparkle.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 50,
      volume: 1.0,
    },
    {
      key: 'fx.sacrifice',
      src: cdnAudio('sound/fx/interaction/sacrifice', 'mp3'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 50,
      volume: 0.9,
    },
    {
      key: 'fx.scavenge',
      src: cdnAudio('sound/fx/interaction/scavenge', 'mp3'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 50,
      volume: 0.9,
    },
    {
      key: 'fx.scribble',
      src: cdnAudio('sound/fx/interaction/scribble', 'mp3'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 10,
      volume: 0.9,
    },
    {
      key: 'fx.signup',
      src: cdnAudio('sound/fx/interaction/signup', 'mp3'),
      bus: 'fx',
      chain: 'presets/success-sparkle.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 10,
      volume: 1.0,
    },
    {
      key: 'fx.success',
      src: cdnAudio('sound/fx/interaction/success', 'mp3'),
      bus: 'fx',
      chain: 'presets/success-sparkle.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 50,
      volume: 1.0,
    },
    {
      key: 'fx.vend',
      src: cdnAudio('sound/fx/interaction/vend', 'mp3'),
      bus: 'fx',
      chain: 'presets/click-tight.json',
      allowOverlap: true,
      maxInstances: 2,
      cooldownMs: 50,
      volume: 1.0,
    },
    {
      key: 'fx.wonderegg',
      src: cdnAudio('sound/fx/interaction/wonderegg', 'mp3'),
      bus: 'fx',
      chain: 'presets/success-sparkle.json',
      allowOverlap: true,
      maxInstances: 4,
      cooldownMs: 50,
      volume: 1.0,
    },
  ],
};

export default registry;
