// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.27.3
// source: snapshot.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { type CallContext, type CallOptions } from "nice-grpc-common";

export const protobufPackage = "snapshot";

/** Base type */
export interface Entity {
  idx: number;
  id: Uint8Array;
}

export interface Component {
  idx: number;
  id: Uint8Array;
}

export interface State {
  packedIdx: number;
  data: Uint8Array;
}

/** Replies */
export interface EntitiesReply {
  entities: Entity[];
}

export interface ComponentsReply {
  components: Component[];
}

export interface BlockReply {
  blockNumber: number;
}

export interface StateReply {
  state: State[];
}

/** Requests */
export interface StateBlockRequest {
}

export interface ComponentsRequest {
  fromIdx: number;
}

export interface EntitiesRequest {
  fromIdx: number;
  numChunks?: number | undefined;
}

export interface StateRequest {
  fromBlock: number;
  numChunks?: number | undefined;
}

function createBaseEntity(): Entity {
  return { idx: 0, id: new Uint8Array(0) };
}

export const Entity: MessageFns<Entity> = {
  encode(message: Entity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.idx !== 0) {
      writer.uint32(8).uint32(message.idx);
    }
    if (message.id.length !== 0) {
      writer.uint32(18).bytes(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Entity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.idx = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Entity>): Entity {
    return Entity.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Entity>): Entity {
    const message = createBaseEntity();
    message.idx = object.idx ?? 0;
    message.id = object.id ?? new Uint8Array(0);
    return message;
  },
};

function createBaseComponent(): Component {
  return { idx: 0, id: new Uint8Array(0) };
}

export const Component: MessageFns<Component> = {
  encode(message: Component, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.idx !== 0) {
      writer.uint32(8).uint32(message.idx);
    }
    if (message.id.length !== 0) {
      writer.uint32(18).bytes(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Component {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComponent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.idx = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Component>): Component {
    return Component.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Component>): Component {
    const message = createBaseComponent();
    message.idx = object.idx ?? 0;
    message.id = object.id ?? new Uint8Array(0);
    return message;
  },
};

function createBaseState(): State {
  return { packedIdx: 0, data: new Uint8Array(0) };
}

export const State: MessageFns<State> = {
  encode(message: State, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.packedIdx !== 0) {
      writer.uint32(8).uint32(message.packedIdx);
    }
    if (message.data.length !== 0) {
      writer.uint32(18).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): State {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.packedIdx = reader.uint32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.data = reader.bytes();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<State>): State {
    return State.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<State>): State {
    const message = createBaseState();
    message.packedIdx = object.packedIdx ?? 0;
    message.data = object.data ?? new Uint8Array(0);
    return message;
  },
};

function createBaseEntitiesReply(): EntitiesReply {
  return { entities: [] };
}

export const EntitiesReply: MessageFns<EntitiesReply> = {
  encode(message: EntitiesReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entities) {
      Entity.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EntitiesReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntitiesReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.entities.push(Entity.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<EntitiesReply>): EntitiesReply {
    return EntitiesReply.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EntitiesReply>): EntitiesReply {
    const message = createBaseEntitiesReply();
    message.entities = object.entities?.map((e) => Entity.fromPartial(e)) || [];
    return message;
  },
};

function createBaseComponentsReply(): ComponentsReply {
  return { components: [] };
}

export const ComponentsReply: MessageFns<ComponentsReply> = {
  encode(message: ComponentsReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.components) {
      Component.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ComponentsReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComponentsReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.components.push(Component.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ComponentsReply>): ComponentsReply {
    return ComponentsReply.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ComponentsReply>): ComponentsReply {
    const message = createBaseComponentsReply();
    message.components = object.components?.map((e) => Component.fromPartial(e)) || [];
    return message;
  },
};

function createBaseBlockReply(): BlockReply {
  return { blockNumber: 0 };
}

export const BlockReply: MessageFns<BlockReply> = {
  encode(message: BlockReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.blockNumber !== 0) {
      writer.uint32(8).uint64(message.blockNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BlockReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBlockReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.blockNumber = longToNumber(reader.uint64());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BlockReply>): BlockReply {
    return BlockReply.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BlockReply>): BlockReply {
    const message = createBaseBlockReply();
    message.blockNumber = object.blockNumber ?? 0;
    return message;
  },
};

function createBaseStateReply(): StateReply {
  return { state: [] };
}

export const StateReply: MessageFns<StateReply> = {
  encode(message: StateReply, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.state) {
      State.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateReply {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateReply();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.state.push(State.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<StateReply>): StateReply {
    return StateReply.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StateReply>): StateReply {
    const message = createBaseStateReply();
    message.state = object.state?.map((e) => State.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStateBlockRequest(): StateBlockRequest {
  return {};
}

export const StateBlockRequest: MessageFns<StateBlockRequest> = {
  encode(_: StateBlockRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateBlockRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateBlockRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<StateBlockRequest>): StateBlockRequest {
    return StateBlockRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<StateBlockRequest>): StateBlockRequest {
    const message = createBaseStateBlockRequest();
    return message;
  },
};

function createBaseComponentsRequest(): ComponentsRequest {
  return { fromIdx: 0 };
}

export const ComponentsRequest: MessageFns<ComponentsRequest> = {
  encode(message: ComponentsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fromIdx !== 0) {
      writer.uint32(8).uint32(message.fromIdx);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ComponentsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComponentsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.fromIdx = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ComponentsRequest>): ComponentsRequest {
    return ComponentsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ComponentsRequest>): ComponentsRequest {
    const message = createBaseComponentsRequest();
    message.fromIdx = object.fromIdx ?? 0;
    return message;
  },
};

function createBaseEntitiesRequest(): EntitiesRequest {
  return { fromIdx: 0, numChunks: undefined };
}

export const EntitiesRequest: MessageFns<EntitiesRequest> = {
  encode(message: EntitiesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fromIdx !== 0) {
      writer.uint32(8).uint32(message.fromIdx);
    }
    if (message.numChunks !== undefined) {
      writer.uint32(16).uint32(message.numChunks);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EntitiesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntitiesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.fromIdx = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.numChunks = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<EntitiesRequest>): EntitiesRequest {
    return EntitiesRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<EntitiesRequest>): EntitiesRequest {
    const message = createBaseEntitiesRequest();
    message.fromIdx = object.fromIdx ?? 0;
    message.numChunks = object.numChunks ?? undefined;
    return message;
  },
};

function createBaseStateRequest(): StateRequest {
  return { fromBlock: 0, numChunks: undefined };
}

export const StateRequest: MessageFns<StateRequest> = {
  encode(message: StateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fromBlock !== 0) {
      writer.uint32(8).uint32(message.fromBlock);
    }
    if (message.numChunks !== undefined) {
      writer.uint32(16).uint32(message.numChunks);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.fromBlock = reader.uint32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.numChunks = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<StateRequest>): StateRequest {
    return StateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StateRequest>): StateRequest {
    const message = createBaseStateRequest();
    message.fromBlock = object.fromBlock ?? 0;
    message.numChunks = object.numChunks ?? undefined;
    return message;
  },
};

export type StateSnapshotServiceDefinition = typeof StateSnapshotServiceDefinition;
export const StateSnapshotServiceDefinition = {
  name: "StateSnapshotService",
  fullName: "snapshot.StateSnapshotService",
  methods: {
    /** Requests the latest block number based on the latest ECS state. */
    getStateBlock: {
      name: "GetStateBlock",
      requestType: StateBlockRequest,
      requestStream: false,
      responseType: BlockReply,
      responseStream: false,
      options: {},
    },
    /** components */
    getComponents: {
      name: "GetComponents",
      requestType: ComponentsRequest,
      requestStream: false,
      responseType: ComponentsReply,
      responseStream: false,
      options: {},
    },
    /** entities */
    getEntities: {
      name: "GetEntities",
      requestType: EntitiesRequest,
      requestStream: false,
      responseType: EntitiesReply,
      responseStream: true,
      options: {},
    },
    /** Get state entries */
    getStateValues: {
      name: "GetStateValues",
      requestType: StateRequest,
      requestStream: false,
      responseType: StateReply,
      responseStream: true,
      options: {},
    },
    /** Get state entry removals */
    getStateRemovals: {
      name: "GetStateRemovals",
      requestType: StateRequest,
      requestStream: false,
      responseType: StateReply,
      responseStream: true,
      options: {},
    },
  },
} as const;

export interface StateSnapshotServiceImplementation<CallContextExt = {}> {
  /** Requests the latest block number based on the latest ECS state. */
  getStateBlock(request: StateBlockRequest, context: CallContext & CallContextExt): Promise<DeepPartial<BlockReply>>;
  /** components */
  getComponents(
    request: ComponentsRequest,
    context: CallContext & CallContextExt,
  ): Promise<DeepPartial<ComponentsReply>>;
  /** entities */
  getEntities(
    request: EntitiesRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<EntitiesReply>>;
  /** Get state entries */
  getStateValues(
    request: StateRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<StateReply>>;
  /** Get state entry removals */
  getStateRemovals(
    request: StateRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<StateReply>>;
}

export interface StateSnapshotServiceClient<CallOptionsExt = {}> {
  /** Requests the latest block number based on the latest ECS state. */
  getStateBlock(request: DeepPartial<StateBlockRequest>, options?: CallOptions & CallOptionsExt): Promise<BlockReply>;
  /** components */
  getComponents(
    request: DeepPartial<ComponentsRequest>,
    options?: CallOptions & CallOptionsExt,
  ): Promise<ComponentsReply>;
  /** entities */
  getEntities(
    request: DeepPartial<EntitiesRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<EntitiesReply>;
  /** Get state entries */
  getStateValues(request: DeepPartial<StateRequest>, options?: CallOptions & CallOptionsExt): AsyncIterable<StateReply>;
  /** Get state entry removals */
  getStateRemovals(
    request: DeepPartial<StateRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<StateReply>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
