name: Sync Files to Target Repo

on:
  push:
    branches:
      - main # Change this if your default branch is "main"
    paths:
      - 'packages/client/src/network/shapes/**' # Only trigger when files in this directory change

env:
  SOURCE_DIR: 'packages/client/src/network/shapes'
  TARGET_DIR: 'shapes'
  TARGET_REPO_OWNER: 'Asphodel-OS'
  TARGET_REPO_NAME: 'kamigotchi-entity-shapes'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          path: source-repo

      - name: Copy files and push
        run: |
          ## SETUP SSH KEY
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          echo "${{secrets.KAMI_SHAPE_DEPLOY_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -la ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add ~/.ssh/id_rsa

          echo "Cloning target repo"  
          git clone git@github.com:${{ env.TARGET_REPO_OWNER }}/${{ env.TARGET_REPO_NAME }}.git
          echo "Copying files"
          # Copy the specified directory
          mkdir -p ./${{ env.TARGET_REPO_NAME }}/${{ env.TARGET_DIR }}
          ls
          ls **/*
          cp -r ./source-repo/${{ env.SOURCE_DIR }}/* ./${{ env.TARGET_REPO_NAME }}/${{ env.TARGET_DIR }}/

          cd ./${{ env.TARGET_REPO_NAME }}

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          # Check for changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Sync Shapes files from Kamigotchi repo

            Source Commit: ${{ github.sha }}
            Workflow: ${{ github.workflow }}
            "
            git push
          else
            echo "No changes to commit"
          fi
