name: Sync Files to Target Repo

on:
  push:
    branches:
      - main
    paths:
      - 'packages/client/src/network/**'
      - 'packages/client/src/workers/**'
      - 'packages/client/src/engine/**'
      - 'packages/client/abi/**'

env:
  SOURCE_DIRS: >-
    packages/client/src/network:network
    packages/client/src/workers:workers
    packages/client/src/engine:engine
    packages/client/abi:abi
  TARGET_REPO_OWNER: 'Asphodel-OS'
  TARGET_REPO_NAME: 'kamigotchi-entity-shapes'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          path: source-repo

      - name: Copy files and push
        run: |
          ## SETUP SSH KEY
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          echo "${{secrets.KAMI_SHAPE_DEPLOY_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -la ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add ~/.ssh/id_rsa

          echo "Cloning target repo"  
          git clone git@github.com:${{ env.TARGET_REPO_OWNER }}/${{ env.TARGET_REPO_NAME }}.git

          # Read SOURCE_DIRS line by line
          echo "${{ env.SOURCE_DIRS }}" | tr ' ' '\n' | while IFS=: read -r source_dir target_dir; do
            if [ -n "$source_dir" ] && [ -n "$target_dir" ]; then
              echo "Processing: source=$source_dir target=$target_dir"
              if [ -d "./source-repo/$source_dir" ]; then
                echo "Copying from $source_dir to $target_dir"
                mkdir -p ./${{ env.TARGET_REPO_NAME }}/$target_dir
                cp -rv ./source-repo/$source_dir/* ./${{ env.TARGET_REPO_NAME }}/$target_dir/
              else
                echo "Source directory ./source-repo/$source_dir does not exist"
                ls -la ./source-repo
              fi
            fi
          done

          cd ./${{ env.TARGET_REPO_NAME }}

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          # Check for changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Sync Shapes files from Kamigotchi repo

            Source Commit: ${{ github.sha }}
            Workflow: ${{ github.workflow }}
            "
            git push
          else
            echo "No changes to commit"
          fi
