name: Publish to public repo

on:
  push:
    branches:
      - main

env:
  TARGET_REPO_OWNER: 'Asphodel-OS'
  TARGET_REPO_NAME: 'kamigotchi-public'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          path: source-repo

      - name: Copy files and push
        run: |
          ## SETUP SSH KEY
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          echo "${{secrets.KAMI_SHAPE_DEPLOY_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -la ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add ~/.ssh/id_rsa

          echo "Cloning target repo"  
          git clone git@github.com:${{ env.TARGET_REPO_OWNER }}/${{ env.TARGET_REPO_NAME }}.git target_repo

          # Remove files from SOURCE
          rm -rf ./source-repo/.github
          rm -rf ./source-repo/.git
          rm -rf ./source-repo/packages/contracts/deployment
          rm -rf ./source-repo/packages/contracts/test

          # Persist TARGET files
          mkdir ./temp_backup
          mv ./target_repo/.github ./target_repo/.git ./target_repo/LICENSE.md ./temp_backup
          rm -rf ./target_repo/*  
          mv ./temp_backup/.git ./temp_backup/.github ./temp_backup/LICENSE.md ./target_repo/  

          cp -r ./source-repo/. ./target_repo/

          cd ./target_repo

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          # Check for changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Publish from Kamigotchi repo

            Source Commit: ${{ github.sha }}
            Workflow: ${{ github.workflow }}
            "
            git push
          else
            echo "No changes to commit"
          fi
